# Generated by Django 4.2 on 2025-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
    ]
