version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: lacrei_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runsslserver 0.0.0.0:8000 --certificate /app/cert.pem --key /app/key.pem
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lacrei_db
      - DEBUG=False
    depends_on:
      - db

volumes:
  postgres_data: