# Generated by Django 4.2 on 2025-08-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(fields=('profissional', 'data'), name='unique_agendamento_profissional'),
        ),
    ]
