# Generated by Django 4.2 on 2025-08-26 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consulta_unique_agendamento_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
